### ISSUE TITLE
Serilog in not working!

### ISSUE THREAD

**Issue by amiradeli** [hamed-shirbandi/TaskoMask#13]
First of all, thank you for knowledge sharing.
Actually, projects did not run properly for me until I added
```
builder.Host.UseSerilog(((ctx, lc) => lc.ReadFrom.Configuration(ctx.Configuration)));
```
to the Program.cs file.
Please let me know if the projects are working properly for you without this line.
I suppose for Serilog to be working properly we have to add UseSerilog but I did not find it anywhere in the code.

**Comment by hamed-shirbandi** [comment]
Hi dear @amiradeli.
That's my fault.
It would be great to have a PR from you to fix it.
Thank you so much.
