### ISSUE TITLE
Move Cards to different position

### ISSUE THREAD

**Issue by SajadJalilian** [hamed-shirbandi/TaskoMask#15]
We can add new cards to the board, but they are now useful if we can not move them around

**Comment by hamed-shirbandi** [comment]
Thanks @SajadJalilian 
You mean the cards should not be able to change their type (ToDo, Doing, Done) through update?

Can you give some more information about the pros and cons?

**Comment by SajadJalilian** [comment]
For example, in Trello we can move cards around, We can have two ToDo cards next to each other
