### ISSUE TITLE
What is the difference between nginix and yarp?

### ISSUE THREAD

**Issue by MohammadrezaAhmadii** [hamed-shirbandi/TaskoMask#150]
which one is better based on speed and performance?

**Comment by hamed-shirbandi** [comment]
Hi @MohammadrezaAhmadii 
As I'm not specialist in this context, I recommend you to find the response through another relevant resources.
Here are some links you can use:
- [YARP project](https://github.com/microsoft/reverse-proxy)
- [nginx documentation](http://nginx.org/docs/)
