### ISSUE TITLE
What is the best reference for microservices?

### ISSUE THREAD

**Issue by MohammadrezaAhmadii** [hamed-shirbandi/TaskoMask#51]
hello , hamed 
1- What is the best reference for microservices?
2- Is DDD necessary for microservices Or it can be based on business? 
3- Is CQRS necessary for microservices Or it can be based on business?

**Comment by hamed-shirbandi** [comment]
Hi @MohammadrezaAhmadii

1- There are many good resources around the web you can find for learning microservices. I recommend you to check the below resources:
- [Pro Microservices in .NET 6 ](https://www.amazon.com/dp/1484278321?tag=uuid10-20)
- [Les Jackson course on YouTube](https://youtu.be/DgVjEo3OGBI)

2 & 3 - It depends on the design and the complexities of the domain. You may use a CRUD base approach for a service and use DDD for others. But, following DDD approach for implementing a complex domain can really help you with your microservice architecture. The boundary around the Aggregates and Bounded Contexts let you simply extract microservices and make it easier to manage the communication between them.
CQRS is very helpful when you want to separate the Read & Write side. So in the read side you can follow a CRUD base approach and a rich domain model for the Write side.

Generally, speaking about the design is really hard until we haven't a specific domain. The domain tells us if a specific design is necessary or not. You can find some good example about your questions through TaskoMask.
