### ISSUE TITLE
Project dependencies don't seem to match architectural documentation

### ISSUE THREAD

**Issue by connellw** [hamed-shirbandi/TaskoMask#7]
Great project! Contains many patterns and approaches I've been learning about recently and it's nice to see them put together.

I was looking at the [architecture documentation](https://github.com/hamed-shirbandi/TaskoMask/wiki/Architecture-Documentation) and noticed the project uses Onion Architecture. There's a diagram showing the Infrastructure and Persistence layers depending on the Application. The bullets below the diagram show that each csproj sits within one of those layers and the namespaces indicate which layer they are in.

I would expect to see a dependency tree **1. Infrastructure -> 2. Application -> 3. Domain**. This appears correct when the [Infrastructure.CrossCutting project has a project reference to the Application.Core](https://github.com/hamed-shirbandi/TaskoMask/blob/master/Src/Libraries/2-Infrastructure/Infrastructure.CrossCutting/Infrastructure.CrossCutting.csproj#L22).

However, when browsing the source, the Libraries directory contains numbered folders which imply a different order **1. Application -> 2. Infrastructure -> 3. Domain**. The [Application.Core project contains a project reference to the Infrastructure.Data project](https://github.com/hamed-shirbandi/TaskoMask/blob/master/Src/Libraries/1-Application/Application.Core/Application.Core.csproj#L26) which matches this approach.

The only usage of this reference I can find is that the [EventStoringBehavior](https://github.com/hamed-shirbandi/TaskoMask/blob/9e990cd0a34549a1ed14d184b6a3f0152720d1c1/Src/Libraries/1-Application/Application.Core/Behaviors/EventStoringBehavior.cs) depends on the IEventStore from the infrastructure.

Can I move that behaviour to the infrastructure project and reverse the dependency here? Happy to raise the PR

**Comment by hamed-shirbandi** [comment]
Hi @connellw .
Thank you for your right advice.
Your vision was very accurate. I appreciate it.
I think it is better to move IEventStore to Domain.Core so we will have these movements:

- IEventStore =>   Domain.Core/Data
- StoredEvent =>  Domain.Core/Event

I would be happy if you make these changes. please send a PR.
You are always welcome to contribute on this project.

**Comment by connellw** [comment]
Ooops, just in time! I had a few minutes so I raised a PR.

When I went to move the EventStore behavior, a few other errors arose and I noticed the `Application.Core` project depends on `Redis.Core`. Redis implementation feels more "infrastructure" to me, and I noticed there was already a dependency on `StackExchange.Redis` in the `Infrastructure.Data` project too. Moving the Redis EventStore behavior and Redis Caching behavior to that same layer seems to make a lot of sense.

Then I saw the ValidationBehavior was left on it's own now. Would that belong in `Infrastructure.CrossCutting`? It does feel like a cross-cutting concern. That way all 3 behaviors are now in the Infrastructure layer.

But I can also understand your solution too of grouping the EventStore with the domain seed work. That might make sense to do as well anyway?

I'd be interested to know your thoughts.

**Comment by hamed-shirbandi** [comment]
As you find, The problem is a wrong  dependency between Application and Infrastructure.
`IEventStore` cause this.
Events are a part of domain so `IEventStore` can move to Domain Layer. It is something like a repository and we can move its implementation to `Infrastructure.Data`. (Repositories are kind of domain services and their implementation move to infrastructrue).

And about behaviors and moving them to `Infrastructure.CrossCutting`. You want to move them because those use some cross cutting but in this layer we just need to config cross cutting concerns, not their usage.
Caching and validating are a part of application and this layer should make decisions for them.

**Comment by connellw** [comment]
I agree that `IEventStore` is analogous to a repository, where it's implementation is an infrastructure concern, but the abstraction can be understood in the domain layer. Happy to move that one.

My thoughts were not that we should move caching because it is a cross-cutting concern, but because the CachingBehavor class requires `IRedisCacheService`, which means the `Application.Core` project depends on `Redis.Core`. Redis is already a dependency of the Infrastructure layer, and moving both the Caching and the EventStore behaviors (both use Redis) to that layer means we can remove the Redis dependency from the Application layer and have Redis only in the `Infrastructure.Data` project.

After moving the 2 Redis behaviors, there was still 1 behavior left in the Application layer - Validation. I moved that to CrossCutting so that all behaviors were in the same layer and because it kind of felt right, but I'm happy to revert that one, I don't feel very strongly about that.

**Comment by connellw** [comment]
Raised PR to move IEventStore as you've suggested.

Do you think we should also:
1. Switch the `1-` and `2-` from the Infrastructure and Application layer folders in Libraries?
2. Find a way to remove direct Redis dependency from the Application layer? Perhaps defining a caching abstraction that we adapt in the Infrastructure?

**Comment by hamed-shirbandi** [comment]
I undrestand your idea to keep behaviors in Infrastructure.CrossCutting but still I believe they are a part of application. After moving IEventStore the main problem will solve so it doesnt need to move application parts to Infrastructure just for removing a third party dependency.

It is just some differences about ideas and I respect your idea.

Thank you for controbuting on this project. If you like to continue please have a look on projects page.

**Comment by connellw** [comment]
I'm not sure I've been very clear. My idea above was **not** to keep all behaviors in `Infrastructure.CrossCutting`. It was to move Redis dependencies into `Infrastructure.Data`.

I understand that you would like to keep behaviors in the Application layer. You could still remove the Redis dependency by creating an abstraction so that Redis is only referenced in the Infrastructure layer.

**Comment by hamed-shirbandi** [comment]
> Raised PR to move IEventStore as you've suggested.
> 
> Do you think we should also:
> 
> 1. Switch the `1-` and `2-` from the Infrastructure and Application layer folders in Libraries?
> 2. Find a way to remove direct Redis dependency from the Application layer? Perhaps defining a caching abstraction that we adapt in the Infrastructure?

1. Surely. I just set those numbers to ordering the folders but yours is more meaningful. Please send a new PR for it.

2. I thought you liked to move all behaviors to Infrastructure because you liked to move `ValidationBehaviour` too. I fully agree with your idea about wrapping Redis dependency but I didn't do that because it's not an important issue for business to keep it away and also I want to keep the things simple as much as possible. For example I made InMemoryBus as a wrapper for MediatR in `Infrastructure.CrossCutting` because it was used every where in Application layer and I do this to remove MediatR dependency in Application. (Of course, this is not complete yet )
