### ISSUE TITLE
user-panel-api-gateway not found

### ISSUE THREAD

**Issue by lurudong** [hamed-shirbandi/TaskoMask#87]
![image](https://user-images.githubusercontent.com/44517714/196425727-cf7a80f0-6c7c-48a4-8ee9-49a7306f9aba.png)

Here's the error:
1>#11 [build  3/10] COPY [src/3-ApiGateways/UserPanel/ApiGateway/ApiGateway.csproj, src/3-ApiGateways/UserPanel/ApiGateway/]
1>#11 sha256:159fb92e71e1b6c3cce8345df51a00e7c02323a4754e65d3c55d834adfbf41ee
1>#11 ERROR: "/src/3-ApiGateways/UserPanel/ApiGateway/ApiGateway.csproj" not found: not found
1>------
1> > [build  3/10] COPY [src/3-ApiGateways/UserPanel/ApiGateway/ApiGateway.csproj, src/3-ApiGateways/UserPanel/ApiGateway/]:
1>------
1>failed to compute cache key: "/src/3-ApiGateways/UserPanel/ApiGateway/ApiGateway.csproj" not found: not found
1>Service 'user-panel-api-gateway' failed to build : Build failed
1>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(523,5): error DT1001: Service 'user-panel-api-gateway' failed to build : Build failed

**Comment by hamed-shirbandi** [comment]
Hi @lurudong
Many Thanks for your report.
The problem was related to a case-sensitive folder name issue.
It was "ApiGateway" on my PC, but "ApiGateWay" on GitHub.
I would be happy to help you with any other question related to the project.
Have a good day.

**Comment by lurudong** [comment]
Hi @hamed-shirbandi 
我的电脑上是"ApiGateway"

**Comment by lurudong** [comment]
Hi @hamed-shirbandi 
Ok
Thank you!!!
